oops, need to exit in order to fail the job

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -55,7 +55,9 @@ jobs:
       - name: Validate Workflow Inputs
         if: ${{ inputs.releaseType == 'custom' && inputs.custom == '' }}
         shell: bash
-        run: echo '::error title=Inputs::Missing version number'
+        run: |
+          echo '::error title=Inputs::Missing version number'
+          exit 1
       - id: action
         name: Determine Action Type
         shell: bash
